import type { Template } from "./types";

export const SEED_TEMPLATES: Template[] = [
  {
    id: "tpl_harvey",
    slug: "harvey-specter",
    title: "Harvey Specter",
    description:
      "Close deals like a closer. Drafts sharp outreach, follow-ups, and objection handlers from your CRM notes.",
    longDescription:
      "Harvey Specter turns messy CRM notes into courtroom-clean sales copy. It drafts first-touch emails, follow-ups, and objection handlers, then queues the next step so your pipeline never goes quiet.",
    category: "Sales",
    author: "Liam",
    authorId: "author_liam",
    priceCents: 0,
    copies: 128,
    views: 424,
    featured: true,
    createdAt: "2026-08-20T10:00:00.000Z",
    integrations: ["gmail", "x", "browser"],
    instructions:
      "Paste the prospect thread + deal stage. Harvey returns subject, body, and a next-step checklist.",
    templateUrl: "https://x.ai/bot/Hs8kQm2nLp4vRx9cWt3Yd",
    status: "published",
  },
  {
    id: "tpl_inbox_triage",
    slug: "inbox-triage",
    title: "Inbox Triage",
    description:
      "Sorts Gmail into action / waiting / archive and drafts replies for the top five threads each morning.",
    longDescription:
      "Inbox Triage scans unread mail, labels by urgency, and drafts concise replies so you open the day already ahead.",
    category: "Productivity",
    author: "Maya",
    authorId: "author_maya",
    priceCents: 1900,
    salePriceCents: 1200,
    stripePriceId: "price_1U9gvDEnhGCqY1izttflx0fe",
    stripeProductId: "prod_VA0xuq5cb1vfmK",
    copies: 412,
    views: 1276,
    featured: true,
    createdAt: "2026-08-18T09:00:00.000Z",
    integrations: ["gmail", "calendar"],
    instructions: "Connect Gmail. Run morning digest. Approve or edit drafts before send.",
    templateUrl: "https://x.ai/bot/It4nBx7wKp2mQs8rVu1Zc",
    status: "published",
  },
  {
    id: "tpl_launch_ops",
    slug: "launch-ops",
    title: "Launch Ops",
    description:
      "Coordinates launch checklists across Notion, Slack, and X so nothing ships half-baked.",
    longDescription:
      "Launch Ops keeps your go-live board honest: owners, blockers, social drafts, and a final ship gate.",
    category: "Ops",
    author: "Noah",
    authorId: "author_noah",
    priceCents: 2900,
    stripePriceId: "price_1U9gvDEnhGCqY1izMFlogbi9",
    stripeProductId: "prod_VA0xLti30aRXZl",
    copies: 86,
    views: 298,
    featured: false,
    createdAt: "2026-08-22T14:00:00.000Z",
    integrations: ["notion", "slack", "x"],
    instructions: "Point it at your Notion launch doc and Slack channel. It posts daily digests.",
    templateUrl: "https://x.ai/bot/Lo9pAe3sDf6gHj1kLm2No",
    status: "published",
  },
  {
    id: "tpl_research_radar",
    slug: "research-radar",
    title: "Research Radar",
    description:
      "Monitors topics across the open web and drops a weekly brief with sources and takeaways.",
    longDescription:
      "Research Radar watches keywords, competitors, and papers, then writes a source-linked briefing you can share.",
    category: "Research",
    author: "Ava",
    authorId: "author_ava",
    priceCents: 2400,
    salePriceCents: 1800,
    stripePriceId: "price_1U9gvEEnhGCqY1izxKl6YWwe",
    stripeProductId: "prod_VA0xA9tvtbS23i",
    copies: 203,
    views: 649,
    featured: true,
    createdAt: "2026-08-12T11:00:00.000Z",
    integrations: ["browser", "notion"],
    instructions: "Add topics + preferred cadence. Radar emails a brief every Monday.",
    templateUrl: "https://x.ai/bot/Rr5tYu8iOp1aSd4fGh7Jk",
    status: "published",
  },
  {
    id: "tpl_support_mirror",
    slug: "support-mirror",
    title: "Support Mirror",
    description:
      "Mirrors ticket tone, suggests macros, and flags churn risk before customers escalate.",
    longDescription:
      "Support Mirror reads ticket history, proposes replies in your voice, and surfaces accounts that need a human.",
    category: "Support",
    author: "Jordan",
    authorId: "author_jordan",
    priceCents: 0,
    copies: 97,
    views: 331,
    featured: false,
    createdAt: "2026-08-25T08:00:00.000Z",
    integrations: ["gmail", "slack"],
    instructions: "Paste ticket thread. Mirror returns a draft + risk flags.",
    templateUrl: "https://x.ai/bot/Sm2nBv5cXz8qWe3rTy6Ui",
    status: "published",
  },
  {
    id: "tpl_finance_pulse",
    slug: "finance-pulse",
    title: "Finance Pulse",
    description:
      "Weekly cash and runway snapshot from your sheets — no dashboard theater.",
    longDescription:
      "Finance Pulse pulls balances and burn into a one-page pulse with alerts when runway dips under your threshold.",
    category: "Finance",
    author: "Priya",
    authorId: "author_priya",
    priceCents: 1500,
    stripePriceId: "price_1U9gvEEnhGCqY1izXBgfPALD",
    stripeProductId: "prod_VA0xLATQJYXFYk",
    copies: 54,
    views: 202,
    featured: false,
    createdAt: "2026-08-10T16:00:00.000Z",
    integrations: ["browser", "notion"],
    instructions: "Share sheet links + alert threshold. Pulse posts Fridays.",
    templateUrl: "https://x.ai/bot/Fp7gHj0kLm3nBq6wEr9Yt",
    status: "published",
  },
  {
    id: "tpl_writer_room",
    slug: "writer-room",
    title: "Writer Room",
    description:
      "Turns a messy outline into publishable drafts with tone locks and SEO notes.",
    longDescription:
      "Writer Room is a quiet editorial partner: outline → draft → headline variants → SEO pass.",
    category: "Writing",
    author: "Elena",
    authorId: "author_elena",
    priceCents: 900,
    stripePriceId: "price_1U9gvFEnhGCqY1izHCAJxd9I",
    stripeProductId: "prod_VA0x64U03hWSNZ",
    copies: 331,
    views: 1033,
    featured: false,
    createdAt: "2026-08-15T12:00:00.000Z",
    integrations: ["notion", "browser"],
    instructions: "Drop outline + audience. Get draft + three headline options.",
    templateUrl: "https://x.ai/bot/Wr1tAs4dFg7hJk0lZx3Cv",
    status: "published",
  },
  {
    id: "tpl_party_bot",
    slug: "party-bot",
    title: "Party Bot",
    description:
      "Plans nights out, polls friends on X/Slack, and books the reservation when the group locks in.",
    longDescription:
      "Party Bot handles the group-chat chaos: venues, votes, calendar holds, and a confirmation ping.",
    category: "Fun",
    author: "Chris",
    authorId: "author_chris",
    priceCents: 0,
    copies: 520,
    views: 1600,
    featured: true,
    createdAt: "2026-08-26T18:00:00.000Z",
    integrations: ["x", "slack", "calendar"],
    instructions: "Add friends + city + vibe. Party Bot runs the poll and books.",
    templateUrl: "https://x.ai/bot/Pb8nMq2wEr5tYu1iOp4As",
    status: "published",
  },
  {
    id: "tpl_code_reviewer",
    slug: "pr-whisperer",
    title: "PR Whisperer",
    description:
      "Reviews pull requests for risk, missing tests, and unclear commit messages before you ship.",
    longDescription:
      "PR Whisperer leaves structured review notes: risk, test gaps, and a suggested summary for the PR body.",
    category: "Engineering",
    author: "Sam",
    authorId: "author_sam",
    priceCents: 2200,
    salePriceCents: 1600,
    stripePriceId: "price_1U9gvFEnhGCqY1izWuEcQbRv",
    stripeProductId: "prod_VA0xj0AK786ip0",
    copies: 178,
    views: 574,
    featured: false,
    createdAt: "2026-08-08T07:00:00.000Z",
    integrations: ["browser", "slack"],
    instructions: "Paste PR URL or diff. Whisperer returns review checklist + comment draft.",
    templateUrl: "https://x.ai/bot/Pr3wHi6sPe9rRe2vIe5wX",
    status: "published",
  },
  {
    id: "tpl_personal_coach",
    slug: "focus-coach",
    title: "Focus Coach",
    description:
      "Daily focus plan from your calendar — protects deep work and nudges when meetings overrun.",
    longDescription:
      "Focus Coach reads your calendar, blocks focus windows, and pings when the day drifts.",
    category: "Personal",
    author: "Riley",
    authorId: "author_riley",
    priceCents: 700,
    stripePriceId: "price_1U9gvFEnhGCqY1izF11vUXjK",
    stripeProductId: "prod_VA0xcUdKAUsCrK",
    copies: 245,
    views: 775,
    featured: false,
    createdAt: "2026-08-21T06:00:00.000Z",
    integrations: ["calendar", "slack"],
    instructions: "Connect calendar. Set focus hours. Coach posts a morning plan.",
    templateUrl: "https://x.ai/bot/Fc4oCu7sHc0aCh3tBo6tS",
    status: "published",
  },
  {
    id: "tpl_growth_loop",
    slug: "growth-loop",
    title: "Growth Loop",
    description:
      "Plans weekly experiments, drafts creatives, and logs winners so marketing stops guessing.",
    longDescription:
      "Growth Loop is a lightweight experiment OS: hypothesis → creative → result → next bet.",
    category: "Marketing",
    author: "Liam",
    authorId: "author_liam",
    priceCents: 3500,
    stripePriceId: "price_1U9gvGEnhGCqY1izPXP0t0uG",
    stripeProductId: "prod_VA0xuOEUKHjjxn",
    copies: 61,
    views: 223,
    featured: true,
    createdAt: "2026-08-05T10:00:00.000Z",
    integrations: ["x", "gmail", "notion"],
    instructions: "Set channel + KPI. Loop proposes three experiments each Monday.",
    templateUrl: "https://x.ai/bot/Gl5oOp8pLo1oOp4pGr7wT",
    status: "published",
  },
  {
    id: "tpl_ops_pager",
    slug: "ops-pager",
    title: "Ops Pager",
    description:
      "Turns incident notes into status updates, owner assignments, and a clean postmortem skeleton.",
    longDescription:
      "Ops Pager keeps incidents calm: draft status, page owners, and scaffold the postmortem while the fire is fresh.",
    category: "Ops",
    author: "Noah",
    authorId: "author_noah",
    priceCents: 0,
    copies: 149,
    views: 487,
    featured: false,
    createdAt: "2026-08-27T20:00:00.000Z",
    integrations: ["slack", "notion"],
    instructions: "Paste incident timeline. Ops Pager returns status + postmortem outline.",
    templateUrl: "https://x.ai/bot/Y7LbP6p5EBFjfdTp69cKr",
    status: "published",
  },
];
